# A msg to hold input from xbox controller. Easier to work with than Joy. 
# A node must be started to intake the Joy messages and output the xbox

# Buttons
int32 a
int32 b
int32 x
int32 y
int32 l_bumper
int32 r_bumper
int32 back
int32 start
int32 xbox
int32 l_stick_press
int32 r_stick_press

# Axes
float32 l_stick_lr
float32 l_stick_ud
float32 l_trigger
float32 r_stick_lr
float32 r_stick_ud
float32 r_trigger
float32 d_pad_lr
float32 d_pad_ud