# A msg to hold input from xbox controller. Easier to work with than Joy. 
# A node must be started to intake the Joy messages and output the xbox

# Buttons
int32 A
int32 B
int32 X
int32 Y
int32 L_BUMPER
int32 R_BUMPER
int32 BACK
int32 START
int32 XBOX
int32 L_STICK_PRESS
int32 R_STICK_PRESS

# Axes
float32 L_STICK_LR
float32 L_STICK_UD
float32 L_TRIGGER
float32 R_STICK_LR
float32 R_STICK_UD
float32 R_TRIGGER
float32 D_PAD_LR
float32 D_PAD_UD